dist: trusty
sudo: false
language: c
cache:
        ccache: true
        directories:
                - dl
addons:
        apt:
                packages:
                        - gcc-avr
                        - avr-libc
                        - cmake
                        - ninja-build
                        - ccache
script:
        - mkdir build
        - cd build
        - cmake -GNinja ../Multiprotocol
        - ninja -v

